### PR TITLE
feat:  added external_proxy_header option 

### PR DESCRIPTION
**Pull request by hdhog**
#885 added new options `external_proxy_header` 

defaults
```
external_proxy_header:
  host: "host"
  proto: "x-forwarded-proto"
```

### CODE REVIEW

**Comment by Eugeny** [comment]
Thank you for the PR! Is your plan to use `host: x-forwarded-host` in your configuration? In this case, do you think it would make more sense to simply add a `trust_proxy_headers` config option and allow fallback from `x-forwarded-host` to the normal `host` so that it works both "internally" and "externally"?

**Comment by lanrat** [comment]
@Eugeny IS there any chance you could merge this or another fix for the host header behind a reverse proxy?

Currently, Warpgate is broken when behind a reverse proxy due to it always adding its internal listen url to the callback.

**Comment by Skyler84** [comment]
I've had Warpgate working fine behind a reverse proxy (Traefik), as long as the `external_host` field is set warpgate redirects correctly!

**Comment by Eugeny** [comment]
Closing in favour of  #907

**Pull request closed without merging**
